import type { Metadata } from 'next'
import { Noto_Sans_KR } from 'next/font/google'
import { TodoProvider } from '@/entities/todo'
import { SideNavigation } from '@/widgets'
import { Toaster } from '@/shared/ui'
// 전역 CSS
import '@/shared/styles/globals.css'
import '@/shared/styles/main.scss'

const NOTO_SANS_KR = Noto_Sans_KR({
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Shardcn UI - TODO-TASKBOARD',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko">
      <body className={NOTO_SANS_KR.className}>
        <TodoProvider>
          <div className="page">
            <SideNavigation />
            <main className="page__main">{children}</main>
          </div>
        </TodoProvider>
        <Toaster richColors={true} />
      </body>
    </html>
  )
}
